### ISSUE TITLE
Provide @types for Typescript

### ISSUE THREAD

**Issue by LucasBrazi06** [wcandillon/react-native-responsive-ui#62]
I just migrated my react-native project and it seems that there is no types provided for your module:
![image](https://user-images.githubusercontent.com/25266945/65325947-872b4e00-dbb0-11e9-80cf-20ab88f155be.png)

I tried 'npm install @types/react-native-responsive-ui' without success.

This shield tsc to find out that you implement React.Component and cut all the inheritance ending with method not defined (setState()...)

Do you plan to provide typing?

**Comment by crutchcorn** [comment]
I will be forking the project to add typings now

**Comment by crutchcorn** [comment]
Wait, I apologize - they already have typings. However, those typings are not matched to the proper directory. I've opened PR to fix this issue #71

**Comment by Dillweed5446** [comment]
Hi, I just added this package to my project, and I'm having the same issue.  PR #71 hasn't been merged yet.
![react-native-responsive-ui](https://user-images.githubusercontent.com/53018748/115485688-ea4bef00-a1f0-11eb-8226-9b38a2620742.png)

**Comment by crutchcorn** [comment]
Temporary workaround is to include this '.d.ts' file in your project 

https://github.com/oceanbit/GitShark/blob/main/src/types/responsive-ui.d.ts

**Comment by wcandillon** [comment]
Is the issue that I use publish a new version of the package? Alternatively I could setup semantic-release to have automatic release.

**Comment by crutchcorn** [comment]
Since the PR was merged, we might want to do a patch release.

Semantic release might be something nice to have. The only concern I have for something like this is that it prevents us from being able to have access to merging PRs and grouping together items for a release at a time.

Is there any way we could do a manual GH action to deploy that we could both access? Otherwise, would I be able to be added as a contributor to the npm package if you're comfortable with that?

**Comment by wcandillon** [comment]
Thanks a lot, invited you as a maintainer there :)
